### ISSUE TITLE
Blank localhost page

### ISSUE THREAD

**Issue by yongzx** [FrameNetBrasil/webtool#4]
When I run `php -S localhost:8000` in the folder `/Users/zhengxinyong/Desktop/webtool/` after performing all the instructions such as `composer install`, my localhost page is blank and my console returns the following error message.
```
Uncaught EMException ' --> Smarty: Unable to load template file '/Users/zhengxinyong/Desktop/webtool/apps/templates/errors/pt_br/.html/public' <-- ' em /Users/zhengxinyong/Desktop/webtool/core/classes/results/minternalerror.php(57)
#0 /Users/zhengxinyong/Desktop/webtool/core/classes/services/http/mresponse.php(232): MInternalError->apply(Object(MRequest), Object(MResponse))
#1 /Users/zhengxinyong/Desktop/webtool/core/classes/mvc/mfrontcontroller.php(138): MResponse->sendResponse(Object(MInternalError), false)
#2 /Users/zhengxinyong/Desktop/webtool/core/classes/manager.php(578): MFrontController->handlerResponse(false)
#3 /Users/zhengxinyong/Desktop/webtool/core/classes/manager.php(568): Manager::handler(false)
#4 /Users/zhengxinyong/Desktop/webtool/index.php(11): Manager::processRequest()
#5 {main}
  thrown in /Users/zhengxinyong/Desktop/webtool/core/classes/results/minternalerror.php on line 57
```

When I use Ampps to load the PHP page with the link `http://localhost/webtool/index.php/webtool/main`, I still obtain a blank page.

**Comment by alankritgupta091099** [comment]
I am also having the same issue

**Comment by elymatos** [comment]
Close for new version.
